# Generated by Django 5.2 on 2025-04-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], default='customer', max_length=10),
        ),
    ]
