# Generated by Django 5.2 on 2025-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Primary Delivery Time (days)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Primary Price'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time',
            field=models.IntegerField(verbose_name='Delivery Time (days)'),
        ),
    ]
