# Generated by Django 5.2 on 2025-04-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offer_delivery_time_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
