# Generated by Django 5.2 on 2025-04-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offer_delivery_time_remove_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='delivery_time',
            new_name='delivery_time_in_days',
        ),
    ]
