# Generated by Django 5.2 on 2025-04-29 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('business_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Business Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Working Hours')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
