# Generated by Django 5.2 on 2025-04-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_userprofile_delete_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='type',
            new_name='profile_type',
        ),
    ]
